//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antecedentes
    {
        public string patologicos { get; set; }
        public string quirurgicos { get; set; }
        public string alergicos { get; set; }
        public string ginecologicos { get; set; }
        public string psiquiatricos { get; set; }
        public string familiares { get; set; }
        public string fk_paciente_rut { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
