//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        public int id { get; set; }
        public byte[] documento { get; set; }
        public string titulo { get; set; }
        public string fk_paciente_rut { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string extension { get; set; }
    
        public virtual Documentos Documentos1 { get; set; }
        public virtual Documentos Documentos2 { get; set; }
    }
}
