//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_GiacamanEntities : DbContext
    {
        public DB_GiacamanEntities()
            : base("name=DB_GiacamanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Antecedentes> Antecedentes { get; set; }
        public virtual DbSet<Atencion> Atencion { get; set; }
        public virtual DbSet<Comuna> Comuna { get; set; }
        public virtual DbSet<Diagnosticos> Diagnosticos { get; set; }
        public virtual DbSet<Documentos> Documentos { get; set; }
        public virtual DbSet<Especialidad> Especialidad { get; set; }
        public virtual DbSet<Estado_civil> Estado_civil { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Registro_diario> Registro_diario { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Salida> Salida { get; set; }
        public virtual DbSet<Tipo_prevision> Tipo_prevision { get; set; }
        public virtual DbSet<Tutor> Tutor { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
