//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Atencion = new HashSet<Atencion>();
            this.Registro_diario = new HashSet<Registro_diario>();
            this.Salida = new HashSet<Salida>();
        }
    
        public string rut { get; set; }
        public string p_nombre { get; set; }
        public string s_nombre { get; set; }
        public string pa_apellido { get; set; }
        public string ma_apellido { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<int> edad { get; set; }
        public Nullable<int> telefono { get; set; }
        public string estado { get; set; }
        public string habitacion { get; set; }
        public string sexo { get; set; }
        public string ocupacion { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public string causal_ingreso { get; set; }
        public Nullable<bool> discapacitado { get; set; }
        public Nullable<int> porcentaje { get; set; }
        public string fk_tutor_rut { get; set; }
        public Nullable<int> fk_prevision { get; set; }
        public Nullable<int> fk_comuna { get; set; }
        public Nullable<int> fk_estado_civil { get; set; }
    
        public virtual Antecedentes Antecedentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atencion> Atencion { get; set; }
        public virtual Comuna Comuna { get; set; }
        public virtual Estado_civil Estado_civil { get; set; }
        public virtual Tipo_prevision Tipo_prevision { get; set; }
        public virtual Tutor Tutor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro_diario> Registro_diario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salida> Salida { get; set; }
    }
}
