//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salida
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string destino { get; set; }
        public string motivo { get; set; }
        public Nullable<System.DateTime> fecha_regreso { get; set; }
        public string fk_paciente_rut { get; set; }
        public string fk_usuario_rut { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
